version: "3"

services:
  mongo:
    image: easternwind/dmarcproject:mongo-dmarc
    environment:
      - MONGODB_ADMIN_USER=root
      - MONGODB_ADMIN_PASS=root
      - MONGODB_APPLICATION_DATABASE=dmarc
      - MONGODB_APPLICATION_USER=user
      - MONGODB_APPLICATION_PASS=root
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

  redis:
    image: redis:4.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  app:
    build:
      context: app/
      args:
        COMPOSER_FLAGS: "--no-scripts --prefer-dist"
    depends_on:
      - mongo
    working_dir: /var/www/html
    env_file:
      - ./app/.env
    volumes:
      - ./app:/var/www/html
      
  web:
    image: easternwind/dmarcproject:nginx-dmarc
    depends_on:
      - app
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html

volumes:
  mongo:
  redis: